config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :merchandises
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
    
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/merchandise.rb
class Merchandise < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
    validates :price, presence: true, numericality: { only_integer: true }
    validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User <ActiveRecord::Base
    has_many :merchandises, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true,
                        uniqueness: { case_sensitive: false },
                        length: {minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                uniqueness: { case_sensitive: false },
                length: { maximum: 105 },
                format: {with: VALID_EMAIL_REGEX }
    validates :mobile, presence: true,
                uniqueness: { case_sensitive: false },
                length: { is: 10 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/merchandises_controller.rb
class MerchandisesController < ApplicationController
    before_action :set_merchandise, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
       @merchandise = Merchandise.new 
    end
    def create
        @merchandise = Merchandise.new(merchandise_params)
        @merchandise.user = current_user
        if @merchandise.save
          flash[:success] = "Your merchandise was successfully uploaded"
          redirect_to merchandise_path(@merchandise)
        else
          render 'new'
          #"render :new"  does the same thing
        end
    end
    
    def show
      @merchandise = Merchandise.find(params[:id])
    end
    def index
      @merchandise = Merchandise.all
    end
    
    def edit
        @merchandise = Merchandise.find(params[:id])
    end
    def update
        if @merchandise.update(merchandise_params)
          flash[:success] = "You merchandise was successfully updated"
          redirect_to article_path(@merchandise)
        else
          render 'edit'
        end 
    end
    
    def destroy
      @merchandise = Merchandise.find(params[:id])
      @merchandise.destroy
      flash[:danger] = "Merchandise was successfully deleted"
      redirect_to merchandises_path
    end
    
    
    private
    def merchandise_params
        params.require(:merchandise).permit(:title, :description, :price, :amount)
    end
    def set_merchandise
      @merchandise = Merchandise.find(params[:id])
    end
    def require_same_user
      if current_user != @merchandise.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own merchandise."
        redirect_to root_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
       
   end
   def create
       user = User.find_by(email: params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
           session[:user_id] = user.id
           flash[:success] = "You have successfully logged in"
           redirect_to user_path(user)
       else
           flash.now[:danger] = "There was something wrong with your login information"
           render 'new'
       end
   end
   def destroy
       session[:user_id] = nil
       flash[:success] = "You have logged out"
       redirect_to root_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]


    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
      flash[:success] = "Welcome to the Flea Market, #{@user.username}"
      redirect_to user_path(@user)

        else
            render 'new'
        end
    end
    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account is updated successfully"
            redirect_to merchandises_path
        else
            render 'edit'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def index
        @users = User.all
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all merchandise created by this user have been deleted"
        redirect_to users_path
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :mobile, :password)
        end

        def set_user
            @user = User.find(params[:id])
        end
        def require_same_user
            if current_user != @user and !current_user.admin?
              flash[:danger] = "You can only edit your own account"
              redirect_to root_path
            end
        end
        
        def require_admin
            if logged_in? and !current_user.admin? 
              flash[:danger] = "Only admin users can perform this action"
              redirect_to root_path
            end
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width; maximum-scale=1.0; user-scalable=1;">
  <title>Flea Market</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--[if lte IE 8]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
  </script><![endif]-->
</head>
<body>
  <div class="wrap">
    <div class="header">
      <div class="header-content">
        <div class="nav-btn">
          <div class="hamburger hamburger--elastic">
            <div class="hamburger-box">
              <div class="hamburger-inner"></div>
            </div>
          </div>
        </div>
        <div class="logo">
          <a href="javascript:;">
            <img src="<%= image_url 'logo.png' %>" />
          </a>
        </div>
        <div class="pc-nav">
          <ul>
            <li class="shop">
              <a href="javascript:;">SHOP</a>
            </li>
            <li class="blog">
              <a href="javascript:;">BLOG</a>
            </li>
            <li class="about">
              <a href="javascript:;">ABOUT</a>
            </li>
            <li class="lookbook">
              <a href="javascript:;">LOOKBOOK</a>
            </li>
          </ul>
        </div>
        <div class="cart">
          <a href="javascript:;">
            <i class="fa fa-shopping-cart"></i>
            <span class="name">CART</span>
          </a>
        </div>
      </div>
    </div>
    <div class="nav">
      <ul>
        <li class="shop">
          <a href="javascript:;">SHOP</a>
        </li>
        <li class="blog">
          <a href="javascript:;">BLOG</a>
        </li>
        <li class="about">
          <a href="javascript:;">ABOUT</a>
        </li>
        <li class="lookbook">
          <a href="javascript:;">LOOKBOOK</a>
        </li>
        <li class="contact">
          <a href="javascript:;">contact us</a>
        </li>
        <li class="help">
          <a href="javascript:;">help</a>
        </li>
        <li class="search">
          <input type="text" placeholder="SEARCH">
        </li>
      </ul>
    </div>
    <div class="category-area">
      <div class="category-content">
        <ul class="category">
          <li>
            <a class="title" href="javascript:;">
              Select a category <i class="fa fa-chevron-down"></i>
            </a>
            <ul class="sub">
              <li class="clothing">
                <a href="javascript:;">clothing</a>
              </li>
              <li class="lifestyle">
                <a href="javascript:;">lifestyle</a>
              </li>
              <li class="prints">
                <a href="javascript:;">prints</a>
              </li>
              <li class="kids">
                <a href="javascript:;">kids</a>
              </li>
              <li class="sale">
                <a href="javascript:;">sale</a>
              </li>
              <li class="gift-guides">
                <a href="javascript:;">gift guides</a>
              </li>
            </ul>
          </li>
          <!-- <li class="category-sub">
            <a class="title" href="javascript:;">
              all <i class="fa fa-chevron-down"></i>
            </a>
            <ul class="sub">
              <li class="clothing">
                <a href="javascript:;">clothing</a>
              </li>
              <li class="lifestyle">
                <a href="javascript:;">lifestyle</a>
              </li>
              <li class="prints">
                <a href="javascript:;">prints</a>
              </li>
              <li class="kids">
                <a href="javascript:;">kids</a>
              </li>
              <li class="sale">
                <a href="javascript:;">sale</a>
              </li>
              <li class="gift-guides">
                <a href="javascript:;">gift guides</a>
              </li>
            </ul>
          </li> -->
        </ul>
        <form class="inputbox">
          <input required="required"/>
          <button type="reset" class="del"></button>
        </form>
      </div>
    </div>
    
  <%= yield %>

    <div class="footer">
      <div class="share">
        <a href="javascript:;">
          Refer a friend &amp; Get $15&nbsp;&nbsp;
          <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
        </a>
      </div>
      <div class="copyright">
        <div>© Ugmonk, Inc. 2016</div>
        <div>Website layout, design elements, content, and all product designs are the property of Ugmonk, Inc.<br>
          and may not be used for any purpose without express written consent of Ugmonk, Inc.</div>
      </div>
    </div>
    <div class="goTop-btn">
      <a href="javascript:;">
        <i class="fa fa-long-arrow-up" aria-hidden="true"></i>
      </a>
    </div>
  </div>
  <div class="container">
    <%= link_to 'Home', root_path %>
    <%= link_to 'Merchandises', merchandises_path %>
    <%= link_to 'Users', users_path %>
    <% if logged_in? %>
      <%= link_to "Edit Your Profile", edit_user_path(current_user) %>
      <%= link_to "View Your Homepage", user_path(current_user) %>
      <%= "Role: Admin" if current_user.admin? %>
      <%= link_to 'Logout', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', login_path %>
      <%= link_to 'Signup', signup_path %>
    <% end %>

    <%= yield %>
  </div>
  <!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flea Market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Merchandises', merchandises_path %>
  <%= link_to 'Users', users_path %>
  <% if logged_in? %>
    <%= link_to "Edit Your Profile", edit_user_path(current_user) %>
    <%= link_to "View Your Homepage", user_path(current_user) %>
    <%= "Role: Admin" if current_user.admin? %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Login', login_path %>
    <%= link_to 'Signup', signup_path %>
  <% end %>

  <%= yield %>
  </div>
  <!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>

app/views/merchandises/_form.html.erb
<%= render 'shared/errors', obj: @merchandise %>
    <div>
    <%= form_for @merchandise do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title, placeholder: "Title of merchandise", autofocus: true %>
        <br />
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, placeholder: "Description the status and spec of your merchandise" %>
        <br />
        <%= f.label :price %>
        <%= f.text_field :price, placeholder: "Price of merchandise" %>
        <br />
        <%= f.label :amount %>
        <%= f.text_field :amount, placeholder: "Amount of merchandise" %>
        <br />
        <%= f.submit %>
   
    <% end %>
    </div>
    <%= link_to "Cancel request and return to merchandise listing", merchandises_path %>

app/views/merchandises/_merchandise.html.erb
<% obj.each do |merchandise| %>
        <div class="merchandise-title">
          <%= link_to merchandise.title, merchandise_path(merchandise) %>
        </div>
        <div class="merchandise-body">
          <%= truncate(merchandise.description, length: 100) %>
          <div class="merchandise-meta-details">
            <small>
              Seller: <%= merchandise.user.username if merchandise.user %>,
              <%= time_ago_in_words(merchandise.created_at) %> ago,
              last update: <%= time_ago_in_words(merchandise.updated_at) %> ago
            </small>
          </div>
        </div>
        <% if logged_in? && (current_user==merchandise.user || current_user.admin?) %>
          <div class="merchandise-actions">
            <%= link_to "Edit this merchandise", edit_merchandise_path(merchandise) %>
            <%= link_to "Delete this merchandise", merchandise_path(merchandise), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete the merchandise?"} %>
          </div>
        <% end %>

        <br />
<% end %>
<%= link_to 'Upload merchandise', new_merchandise_path %>

app/views/merchandises/edit.html.erb
<h1 align="center">Edit Existing Merchandise</h1>

<%= render 'form' %>

app/views/merchandises/index.html.erb
<h1 align="center">Listing All Merchandise</h1>
<%= render 'merchandise', obj: @merchandise %>

app/views/merchandises/new.html.erb
<h1>Upload New Merchandises</h1>
<%= render 'form'%>

app/views/merchandises/show.html.erb
<h2 align="center">Title: <%= @merchandise.title %></h2>
  <h4></h4>
  <hr>
  <%= simple_format(@merchandise.description) %>
  <br />
  <p>Price: <%= @merchandise.price%></p>
  <p>Amount: <%= @merchandise.amount%></p>
  <% if @merchandise.user %>
    <ul class="listing">
    <li class="merchandise-title">Uploaded by:
      <%= link_to @merchandise.user.username, user_path(@merchandise.user) %>
    </li>
    <li><small><%= pluralize(@merchandise.user.merchandises.count, "merchandise") if @merchandise.user.merchandises %></small></li>
    </ul>
  <% end %>
  <div class="merchandise-actions">
    <% if logged_in? && (current_user == @merchandise.user || current_user.admin?) %>
      <%= link_to "Edit this merchandise", edit_merchandise_path(@merchandise) %>
      <%= link_to "Delete this merchandise", merchandise_path(@merchandise), method: :delete, 
                                        data: { confirm: "Are you sure you want to delete the merchandise?"} %>
    <% end %>
    <%= link_to "View all merchandises", merchandises_path %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
  <%= pluralize(obj.errors.count, "error") %>
  prohibited this article from being saved:
  <% obj.errors.full_messages.each do |msg| %>
  <%= msg %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<%= f.label :username %>
<%= f.text_field :username, placeholder: "Enter username", autofocus: true %>
<br />
<%= f.label :email %>
<%= f.email_field :email, placeholder: "Enter email" %>
<br />
<%= f.label :mobile %>
<%= f.text_field :mobile, placeholder: "Enter mobile" %>
<br />
<%= f.label :password %>
<%= f.password_field :password, placeholder: "Enter password" %>
<br />
<%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>

<% end %>

[ <%= link_to "Cancel request and return to home", root_path %> ]

app/views/users/edit.html.erb
<h1 align="center">Edit You Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Users Listing</h1>
<div align="center">
    <% @users.each do |user| %>
    <div>
        <p class="merchandise-title"><%= link_to user.username, user_path(user) %>
        <br />
        <small><%= pluralize(user.merchandises.count, "merchandise") if user.merchandises %></small>
        <br />
        <% if logged_in? && current_user.admin?%>
          <%= link_to "Delete this user", user_path(user), method: :delete,
              data: { confirm:"Are you sure you want to delete the user and all their merchandises?"} %>
        <% end %>
        </p>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Flea Market</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<h4 align="center">
<%= @user.username %>'s merchandises
</h4>
<%= render 'merchandises/merchandise', obj: @user.merchandises %>

app/views/welcome/index2.html.erb
<h1>Hello! This is flea market</h1>
<ul>
    <li><%= link_to 'Browse all the merchandise', merchandises_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Upload merchandise", new_merchandise_path %></li>
    <% end %>
</ul>
<ul>
    <% if !logged_in? %>
        <li><%= link_to 'Create your own acoount', signup_path %></li>
    <% end %>
    <li><%= link_to 'View all our members', users_path %></li>
</ul>